### ISSUE TITLE
Question: Image size limit

### ISSUE THREAD

**Issue by equinusocio** [spinningarrow/zoom-vanilla.js#43]
Hi, just a question, is it possible to set a max width/height or a max scale ratio to the zoomed image? 

PS: Maybe this can be a feature request..

**Comment by heavybeard** [comment]
From what I remember it is not possible, but I have not followed this repo for a while
@spinningarrow have you add this feature?

**Comment by rafal-olszewski** [comment]
Didn't test it, but you could try modifying the CSS like so:

```css
.zoom-img-wrap img.zoom-img {
  max-width: 80%;
}
```
